src/Entity/Dog.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DogRepository")
 * @ORM\Table(name="dogs")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity("pedigree_reg_no")
 */
class Dog
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(groups={"registration"}, message="This dog has already been registered to the show")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank()
     */
    private $registered_name;

    /**
     * @ORM\Column(type="string", length=20, unique=true)
     * @Assert\NotBlank()
     */
    private $pedigree_reg_no;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    private $sex;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    private $color;

    /**
     * @ORM\Column(type="date")
     */
    private $date_of_birth;

    /**
     * @ORM\OneToMany(targetEntity="Title", mappedBy="dog", cascade={"persist", "remove"}, orphanRemoval=true)
     * @Assert\Valid()
     */
    private $titles;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    private $chip_tattoo_no;

    /**
     * @ORM\Column(type="string")
     */
    private $sire;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    private $dam;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    private $breeder;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    private $name_of_club;

    /**
     * @ORM\ManyToOne(targetEntity="Owner", inversedBy="dogs")
     * @ORM\JoinColumn(name="owner_id", referencedColumnName="id")
     */
    private $owner;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity="Image", mappedBy="dog", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $files;

    /**
     * Many Registration to one Dog
     * @ORM\OneToMany(targetEntity="Registration", mappedBy="dog")
     */
    private $registrations;

    public function __construct()
    {
        $this->titles = new ArrayCollection();
        $this->files = new ArrayCollection();
        $this->registrations = new ArrayCollection();
    }

    public function __toString()
    {
        return '';

    }


    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getRegisteredName()
    {
        return $this->registered_name;
    }

    /**
     * @param mixed $registered_name
     */
    public function setRegisteredName($registered_name): void
    {
        $this->registered_name = $registered_name;
    }

    /**
     * @return mixed
     */
    public function getPedigreeRegNo()
    {
        return $this->pedigree_reg_no;
    }

    /**
     * @param mixed $pedigree_reg_no
     */
    public function setPedigreeRegNo($pedigree_reg_no): void
    {
        $this->pedigree_reg_no = $pedigree_reg_no;
    }

    /**
     * @return mixed
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     * @param mixed $sex
     */
    public function setSex($sex): void
    {
        $this->sex = $sex;
    }

    /**
     * @return mixed
     */
    public function getColor()
    {
        return $this->color;
    }

    /**
     * @param mixed $color
     */
    public function setColor($color): void
    {
        $this->color = $color;
    }

    /**
     * @return mixed
     */
    public function getTitles()
    {
        return $this->titles;
    }


    public function addTitle(Title $title)
    {
       if (!$this->titles->contains($title)) {
            $this->titles->add($title);
            $title->setDog($this);
        }
        return $this->titles;
    }

    public function removeTitle(Title $title)
    {
        if (!$this->titles->contains($title)) {
            return;
        }
        $this->titles->removeElement($title);
        // needed to update the owning side of the relationship!
        $title->setDog(null);
    }

    /**
     * @return mixed
     */
    public function getFiles()
    {
        return $this->files;
    }


    public function addFile(Image $file)
    {
        if (!$this->files->contains($file)) {
            $this->files->add($file);
            $file->setDog($this);
        }
        return $this->files;
    }

    public function removeFile($file)
    {
//        foreach ($titles as $key => $title) {
        $this->files->removeElement($file);
//        }
        return $this->files;

    }

    /**
     * @return mixed
     */
    public function getRegistrations()
    {
        return $this->registrations;
    }

    public function addRegistration(Registration $registration)
    {
        if (!$this->registrations->contains($registration)) {
            $this->registrations->add($registration);
            $registration->setDog($this);
        }
        return $this->registrations;
    }

    public function removeRegistration($registration)
    {
//        foreach ($titles as $key => $title) {
        $this->registrations->removeElement($registration);
//        }
        return $this->registrations;

    }

    /**
     * @return mixed
     */
    public function getDateOfBirth()
    {
        return $this->date_of_birth;
    }

    /**
     * @param mixed $date_of_birth
     */
    public function setDateOfBirth($date_of_birth): void
    {
        $this->date_of_birth = $date_of_birth;
    }


    /**
     * @return mixed
     */
    public function getChipTattooNo()
    {
        return $this->chip_tattoo_no;
    }

    /**
     * @param mixed $chip_tattoo_no
     */
    public function setChipTattooNo($chip_tattoo_no): void
    {
        $this->chip_tattoo_no = $chip_tattoo_no;
    }

    /**
     * @return mixed
     */
    public function getSire()
    {
        return $this->sire;
    }

    /**
     * @param mixed $sire
     */
    public function setSire($sire): void
    {
        $this->sire = $sire;
    }

    /**
     * @return mixed
     */
    public function getDam()
    {
        return $this->dam;
    }

    /**
     * @param mixed $dam
     */
    public function setDam($dam): void
    {
        $this->dam = $dam;
    }

    /**
     * @return mixed
     */
    public function getBreeder()
    {
        return $this->breeder;
    }

    /**
     * @param mixed $breeder
     */
    public function setBreeder($breeder): void
    {
        $this->breeder = $breeder;
    }

    /**
     * @return mixed
     */
    public function getNameOfClub()
    {
        return $this->name_of_club;
    }

    /**
     * @param mixed $name_of_club
     */
    public function setNameOfClub($name_of_club): void
    {
        $this->name_of_club = $name_of_club;
    }

    /**
     * @return mixed
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * @param mixed $owner
     */
    public function setOwner($owner): void
    {
        $this->owner = $owner;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * @param mixed $created_at
     */
    public function setCreatedAt($created_at): void
    {
        $this->created_at = $created_at;
    }

    /**
     * @return mixed
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * @param mixed $updated_at
     */
    public function setUpdatedAt($updated_at): void
    {
        $this->updated_at = $updated_at;
    }


    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function updateTimestamps()
    {
        $this->updated_at = new \DateTime('now');

        if ($this->getCreatedAt() === null) {
            $this->created_at = new \DateTime('now');
        }
    }


}

src/Entity/Owner.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OwnerRepository")
 * @ORM\Table(name="owners")
 * @ORM\HasLifecycleCallbacks()
 */
class Owner
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * One Owner has One User.
     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="owner")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    private $surname;

    /**
     * @ORM\Column(type="string")
     * @Assert\Length(
     *      min = 8,
     *      max = 15,
     *      minMessage = "Your phone number must be at least {{ 8 }} characters long",
     *      maxMessage = "Your phone number cannot be longer than {{ 15 }} characters"
     * )
     */
    private $phone;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    private $address;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    private $city;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    private $country;

    /**
     * One Owner has Many Dogs.
     * @ORM\OneToMany(targetEntity="Dog", mappedBy="owner")
     */
    private $dogs;


    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __toString()
    {
        return '';
    }

    public function __construct() {
        $this->dogs = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     * @return Owner
     */
    public function setUser($user)
    {
        $this->user = $user;
        return $this;
    }


    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name): void
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getSurname()
    {
        return $this->surname;
    }

    /**
     * @param mixed $surname
     */
    public function setSurname($surname): void
    {
        $this->surname = $surname;
    }

    /**
     * @return mixed
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * @param mixed $phone
     */
    public function setPhone($phone): void
    {
        $this->phone = $phone;
    }

     /**
     * @return mixed
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * @param mixed $address
     */
    public function setAddress($address): void
    {
        $this->address = $address;
    }

    /**
     * @return mixed
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param mixed $city
     */
    public function setCity($city): void
    {
        $this->city = $city;
    }

    /**
     * @return mixed
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * @param mixed $country
     */
    public function setCountry($country): void
    {
        $this->country = $country;
    }

    /**
     * @return mixed
     */
    public function getDogs()
    {
        return $this->dogs;
    }


    public function addDog(Dog $dog)
    {
        if (!$this->dogs->contains($dog)) {
            $this->dogs->add($dog);
            $dog->setOwner($this);
        }
        return $this->dogs;
    }

    public function removeDog($dog)
    {
//        foreach ($titles as $key => $title) {
        $this->dogs->removeElement($dog);
//        }
        return $this->dogs;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * @param mixed $created_at
     */
    public function setCreatedAt($created_at): void
    {
        $this->created_at = $created_at;
    }

    /**
     * @return mixed
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * @param mixed $updated_at
     */
    public function setUpdatedAt($updated_at): void
    {
        $this->updated_at = $updated_at;
    }
    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function updateTimestamps()
    {
        $this->updated_at = new \DateTime('now');

        if ($this->getCreatedAt() === null) {
            $this->created_at = new \DateTime('now');
        }
    }
    public function getFullName()
    {
        return trim($this->getSurname(). ' '.$this->getName());
    }
}

src/Controller/DiplomaController.php
<?php

namespace App\Controller;

use App\Entity\Diploma;
use App\Entity\Registration;
use App\Form\DiplomaType;
use App\Repository\DiplomaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/diploma")
 */
class DiplomaController extends Controller
{
    /**
     * @Route("/", name="diploma_index", methods="GET")
     */
    public function index(DiplomaRepository $diplomaRepository): Response
    {
        $diplomas = $diplomaRepository->findAll();

        return $this->render('diploma/index.html.twig', [
            'diplomas' => $diplomas,
        ]);
    }

    /**
     * @Route("/new/{registration}", name="diploma_new", methods="GET|POST")
     */
    public function new(Request $request, Registration $registration): Response
    {
        $diploma = new Diploma();

        $form = $this->createForm(DiplomaType::class, $diploma);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $diploma->setRegistration($registration);
            $em->persist($diploma);
            $em->flush();

            return $this->redirectToRoute('diploma_index');
        }

        return $this->render('diploma/new.html.twig', [
            'diploma' => $diploma,
            'registration' => $registration->getId(),
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="diploma_show", methods="GET")
     */
    public function show(Diploma $diploma): Response
    {
        return $this->render('diploma/show.html.twig', ['diploma' => $diploma]);
    }

    /**
     * @Route("/{id}/edit", name="diploma_edit", methods="GET|POST")
     */
    public function edit(Request $request, Diploma $diploma): Response
    {
        $form = $this->createForm(DiplomaType::class, $diploma);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('diploma_edit', ['id' => $diploma->getId()]);
        }

        return $this->render('diploma/edit.html.twig', [
            'diploma' => $diploma,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="diploma_delete", methods="DELETE")
     */
    public function delete(Request $request, Diploma $diploma): Response
    {
        if ($this->isCsrfTokenValid('delete'.$diploma->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($diploma);
            $em->flush();
        }

        return $this->redirectToRoute('diploma_index');
    }

    /**
     * @Route("/{id}/pdf", name="diploma_pdf")
     */
    public function pdf(Request $request, Diploma $diploma): Response
    {
        $snappy = $this->get('knp_snappy.pdf');

        $html = $this->renderView('diploma/diploma_pdf.html.twig', [
            'diploma' => $diploma,
        ]);

        $filename = 'diploma_pdf';



        return new Response(
            $snappy->getOutputFromHtml($html),
            200,
            array(
                'Content-Type'          => 'application/pdf',
                'Content-Disposition'   => 'inline; filename="'.$filename.'.pdf"'
            )
        );
    }
}

templates/diploma/_delete_form.html.twig
<form method="post" action="{{ path('diploma_delete', {'id': diploma.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ diploma.id) }}">
    <button class="btn">Delete</button>
</form>

templates/diploma/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_label(form.titles) }}
 {#store the prototype on the data-prototype attribute #}
<ul id="title-fields-list"
    data-prototype="{{ form_widget(form.titles.vars.prototype)|e }}"
    data-widget-tags="{{ '<li></li>'|e }}">
    {% for titleField in form.titles %}
        <li>
            {{ form_errors(titleField) }}
            {{ form_row(titleField) }}
        </li>
    {% endfor %}
</ul>


<button type="button"
        class="add-another-collection-widget"
        data-list="#title-fields-list">Add title</button>
<button type="button"
        class="remove-another-collection-widget"
        data-list="#title-fields-list">Remove title</button>

    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/diploma/diploma_pdf.html.twig
<head>
    <meta charset="utf-8">
    <title>Diploma pdf</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <style>
        .container {
            margin-left:40px;
        }
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td{
            border: 1px solid grey;
            text-align: left;
            height: 40px;
        }

        footer{
            position: fixed;
            height: 80px;
            bottom: 0;
            left: 0;
            right: 0;
            margin-bottom: 0;
            font-size: medium;
            text-align: center;
        }
        body{
            margin-bottom: 10px;
        }
        h1 {
            text-align: center;
            padding-top: 30px;
            font-size: 50px;
        }

        #results td {
            padding: 20px;
            font-size:20px;
        }
        #titles td{
            padding: 15px;
        }
        #cell-1 {
            width: 20%;
        }
        #cell-2{
            width:45%
        }
        #cell-3 {
            width: 15%
        }
        #cell-5, #cell-7, #cell-9 {
            width:30%;
        }
        #cell-8 {
            font-size: x-large;
            text-align: center;
        }


    </style>
</head>

<div class="container" style ="max-width: 920px;">
    <header>
        <img height="200" src="https://sites.google.com/site/labmklt/_/rsrc/1327487202318/config/customLogo.gif?revision=14"/>
    </header>

    <h1>DIPLOMAS</h1>
    <div class="table-container">
            <div id="show-name" style="text-align: center; font-size: 21px; line-height: 150%">{{ diploma.registration.show.showName | upper }}</div>
            <br>
            <div id ="show-city" style="text-align: center; font-size: 25px">{{ diploma.registration.show.city | capitalize }}</div>
            <hr>
            <div id="show-date" style="text-align: center; font-size: 25px; padding-bottom: 40px">({{ diploma.registration.show.dateShow ? diploma.registration.show.dateShow|date('Y-m-d') : '' }})</div>
        <table class="table-show">
            <tbody>
            <tr>
                <td style="font-size: 20px; padding: 10px; width:35%;">Anglų buldogas (Bulldog)</td>
                <td style="font-size: 35px;text-align: center; padding: 10px;">{{ diploma.registration.dog.registeredName | upper}}</td>
            </tr>
            <tr>
                <td style="font-size: 20px; padding: 10px">Katalogo Nr. / Catalogue No. :</td>
                <td style="font-size: 20px;text-align: center; padding: 10px;">23</td>
            </tr>
            <tr>
                <td style="padding: 10px; font-size: 25px; text-align: center">{{ diploma.registration.dog.pedigreeRegNo }}</td>
                <td style="font-size: 25px; padding: 10px; text-align: center">{{ diploma.registration.dog.owner.name | capitalize }} {{ diploma.registration.dog.owner.surname |capitalize }} </td>
            </tr>
            <td style="padding: 10px; text-align: center">Registracijos nr. / Pedigree No.</td>
            <td style="padding: 10px; text-align: center">Savininkas / Owner</td>
            </tbody>
        </table>
            <table id="dog-info">
                <tbody>
                <tr>
                    <td style="padding: 10px; font-size: 25px; text-align: center">{{ diploma.registration.dog.dateOfBirth ? diploma.registration.dog.dateOfBirth|date('Y-m-d') : '' }}</td>
                    <td style="padding: 10px; font-size: 25px;text-align: center">{{diploma.registration.dog.sex  }}</td>
                    {% if diploma.registration.class.classTitle is defined %}
                    <td style="padding: 10px; font-size: 25px;text-align: center">{{ diploma.registration.class.classTitle }}</td>
                    {% else %}
                    <td></td>
                    {% endif %}
                </tr>
                <tr>
                    <td style="padding: 10px; text-align: center">Gimimo data / DOB</td>
                    <td style="padding: 10px; text-align: center">Lytis / Sex</td>
                    <td style="padding: 10px; text-align: center">Klasė / Class</td>
                </tr>
                </tbody>
            </table>
        </table>
        <table id="results">
            <tbody>
            <tr>
                <td id="cell-1">Įvertinimas / Evaluation: </td>
                {% if  diploma.result.grade is defined %}
                    <td id="cell-2">{{ diploma.result.grade }}</td>
                {% else %}
                    <td id="cell-2"></td>
                {% endif %}
                <td id="cell-3">Vieta / Place: </td>
                {% if  diploma.result.place is defined %}
                    <td id="cell-4">{{ diploma.result.place }}</td>
                {% else %}
                    <td id="cell-4"></td>
                {% endif %}
            </tr>
            </tbody>
        </table>
        <table id="titles" >
            <tbody>
            <tr>
                <td id="cell-5"> Titulai / Titles: </td>
               <td id="cell-6"></td>
            </tr>
            <tr>
                <td id="cell-7"> Teisėjas / Judge: </td>
                <td id="cell-8"> {% for judge in diploma.registration.show.judges %}
                    {{ judge.fullName }} |
                {% endfor %}</td>
            </tr>
            <tr>
                <td id="cell-9">Asistentas / Ring steward:</td>
                <td id="cell-10"> </td>
            </tr>
            </tbody>
        </table>
    </div>



    {{ include('_pdffooter.html.twig') }}

</div>

templates/diploma/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Diploma{% endblock %}

{% block body %}
    <div class="container-fluid symfony-form app-form">
    <h1>Edit Diploma</h1>

    {{ include('diploma/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('diploma_index') }}">back to list</a>

    {{ include('diploma/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/diploma/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Diploma index{% endblock %}

{% block body %}
    <div class="container-fluid symfony-form app-form">

<h1>Diploma index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date of issue</th>
                <th>Dog awarded</th>
                <th>Show</th>
                <th>Owner</th>
                <th>actions</th>
                <th>Delete</th>
                <th>Generate pdf</th>
            </tr>
        </thead>
        <tbody>
        {% for diploma in diplomas %}
            <tr>
                <td>{{ diploma.id }}</td>
                <td>{{ diploma.date ? diploma.date |date('Y-m-d') : '' }}</td>
                {% if diploma.registration.dog.registeredName is defined %}
                <td>{{ diploma.registration.dog.registeredName }}</td>
                {% else %}
                    <td>Not available</td>
                    {% endif %}
                {% if  diploma.registration.show.placeAndTime is defined %}
                <td>{{ diploma.registration.show.placeAndTime }}</td>
                {% else %}
                    <td>Not available</td>
                    {% endif %}
                {% if diploma.registration.dog.owner.fullName is defined %}
                <td>{{ diploma.registration.dog.owner.fullName }}</td>
                {% else %}
                    <td>Not avilable</td>
                {% endif %}
                <td>
                    <a href="{{ path('diploma_show', {'id': diploma.id}) }}">show</a>
                    <a href="{{ path('diploma_edit', {'id': diploma.id}) }}">edit</a>
                </td>
                <td>
                    {{ include('diploma/_delete_form.html.twig') }}
                </td>
                <td>
                    <a href="{{ path('diploma_pdf', {'id': diploma.id}) }}">Generate pdf</a>
                </td>
            </tr>

            {% else %}
            <tr>
                <td colspan="2">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('registration_index')}}">Create new diploma</a>
    </div>
{% endblock %}

templates/diploma/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Diploma{% endblock %}

{% block body %}
    <div class="container-fluid symfony-form app-form">

<h1>Create new Diploma</h1>

    {{ include('diploma/_form.html.twig') }}

    <a href="{{ path('diploma_index') }}">back to list</a>
    </div>
{% endblock %}

templates/diploma/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Diploma{% endblock %}

{% block body %}
    <div class="container-fluid symfony-form app-form">

    <h1>Diploma</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Diploma Id</th>
                <td>{{ diploma.id }}</td>
            </tr>
        <tr>
            <th>Diploma No.</th>
            <td>{{ diploma.number }}</td>
        </tr>
        <tr>
            <th>Diploma date</th>
            <td>    {{ diploma.date ? diploma.date |date('Y-m-d') : '' }}</td>
        </tr>
            <tr>
                <th>Bulldog</th>
                <td>{{ diploma.registration.dog.registeredName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('diploma_index') }}">back to list</a>

    <a href="{{ path('diploma_edit', {'id': diploma.id}) }}">edit</a>

    {{ include('diploma/_delete_form.html.twig') }}
    </div>
{% endblock %}